services:
  - type: web
    name: rsm-automotriz
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rsm-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
