 services:
  - type: web
    name: rsm-automotriz
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rsm_automotriz_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0

databases:
  - name: rsm_automotriz_db
    plan: free
    databaseName: rsm_automotriz
    user: rsm_automotriz_user